/**
 * Itinerary roster — single source of truth for the itinerary grid
 * (itineraries.html) and the itinerary detail template (itinerary.html?slug=).
 *
 * Rebuilt from the client's 16 named route maps (one per itinerary, region
 * baked into the file name). Two itineraries can share the same theme name
 * across two regions (e.g. "Sultans and Tarsiers" in both Moluccas and
 * Sulawesi) — those are two separate itineraries with their own slug, page
 * and route image, not one shared one.
 *
 * TODO: only the name, region and route map (see itinerary-routes-data.js)
 * are real so far — nights/level/season/teaser/description/detailExtra and
 * the photo below are all placeholders pending the client's real copy and
 * photography for each route.
 */

const ITINERARIES = [
  // ---- Moluccas ----
  {
    slug: "moluccas-forts-and-forests",
    name: "Forts and Forests",
    eyebrow: "Moluccas",
    region: "Moluccas",
    nights: 7,
    level: "All certified levels",
    season: "TODO: season",
    teaser: "TODO: one-line teaser for Forts and Forests (Moluccas).",
    description: "TODO: full description for Forts and Forests, a Moluccas route.",
    detailExtra: "TODO: extra detail paragraph for Forts and Forests (Moluccas).",
    image: "banda-sea",
    imageAlt: "A volcanic island silhouette at sunset, with a traditional boat on calm water.",
    photoCaption: "Forts and Forests, Moluccas",
  },
  {
    slug: "moluccas-corals-and-cloves",
    name: "Corals and Cloves",
    eyebrow: "Moluccas",
    region: "Moluccas",
    nights: 7,
    level: "All certified levels",
    season: "TODO: season",
    teaser: "TODO: one-line teaser for Corals and Cloves (Moluccas).",
    description: "TODO: full description for Corals and Cloves, a Moluccas route.",
    detailExtra: "TODO: extra detail paragraph for Corals and Cloves (Moluccas).",
    image: "manta-ray",
    imageAlt: "A diver and a manta ray over a reef.",
    photoCaption: "Corals and Cloves, Moluccas",
  },
  {
    slug: "moluccas-spices-and-snakes",
    name: "Spices and Snakes",
    eyebrow: "Moluccas",
    region: "Moluccas",
    nights: 7,
    level: "Advanced divers",
    season: "TODO: season",
    teaser: "TODO: one-line teaser for Spices and Snakes (Moluccas).",
    description: "TODO: full description for Spices and Snakes, a Moluccas route.",
    detailExtra: "TODO: extra detail paragraph for Spices and Snakes (Moluccas).",
    image: "diver-reef",
    imageAlt: "A diver over a coral reef.",
    photoCaption: "Spices and Snakes, Moluccas",
  },
  {
    slug: "moluccas-sultans-and-tarsiers",
    name: "Sultans and Tarsiers",
    eyebrow: "Moluccas",
    region: "Moluccas",
    nights: 7,
    level: "All certified levels",
    season: "TODO: season",
    teaser: "TODO: one-line teaser for Sultans and Tarsiers (Moluccas).",
    description: "TODO: full description for Sultans and Tarsiers, a Moluccas route.",
    detailExtra: "TODO: extra detail paragraph for Sultans and Tarsiers (Moluccas).",
    image: "dive-guide",
    imageAlt: "A dive guide briefing the group before a dive.",
    photoCaption: "Sultans and Tarsiers, Moluccas",
  },

  // ---- Papua ----
  {
    slug: "papua-corals-and-cloves",
    name: "Corals and Cloves",
    eyebrow: "Papua",
    region: "Papua",
    nights: 8,
    level: "All certified levels",
    season: "TODO: season",
    teaser: "TODO: one-line teaser for Corals and Cloves (Papua).",
    description: "TODO: full description for Corals and Cloves, a Papua route.",
    detailExtra: "TODO: extra detail paragraph for Corals and Cloves (Papua).",
    image: "raja-ampat",
    imageAlt: "Aerial view of karst islands and turquoise lagoons in Raja Ampat, West Papua.",
    photoCaption: "Corals and Cloves, Papua",
  },
  {
    slug: "papua-forts-and-forests",
    name: "Forts and Forests",
    eyebrow: "Papua",
    region: "Papua",
    nights: 8,
    level: "All certified levels",
    season: "TODO: season",
    teaser: "TODO: one-line teaser for Forts and Forests (Papua).",
    description: "TODO: full description for Forts and Forests, a Papua route.",
    detailExtra: "TODO: extra detail paragraph for Forts and Forests (Papua).",
    image: "raja-ampat",
    imageAlt: "Aerial view of karst islands and turquoise lagoons in Raja Ampat, West Papua.",
    photoCaption: "Forts and Forests, Papua",
  },
  {
    slug: "papua-four-kings",
    name: "Four Kings",
    eyebrow: "Papua",
    region: "Papua",
    nights: 8,
    level: "All certified levels",
    season: "TODO: season",
    teaser: "TODO: one-line teaser for Four Kings — Raja Ampat, \"four kings\", in Papua.",
    description: "TODO: full description for Four Kings, a Papua route.",
    detailExtra: "TODO: extra detail paragraph for Four Kings (Papua).",
    image: "raja-ampat",
    imageAlt: "Aerial view of karst islands and turquoise lagoons in Raja Ampat, West Papua.",
    photoCaption: "Four Kings, Papua",
  },
  {
    slug: "papua-southern-king",
    name: "Southern King",
    eyebrow: "Papua",
    region: "Papua",
    nights: 9,
    level: "Advanced divers",
    season: "TODO: season",
    teaser: "TODO: one-line teaser for Southern King (Papua).",
    description: "TODO: full description for Southern King, a Papua route.",
    detailExtra: "TODO: extra detail paragraph for Southern King (Papua).",
    image: "chef-galley",
    imageAlt: "Waow 2's chef at work in the galley.",
    photoCaption: "Southern King, Papua",
  },
  {
    slug: "papua-tale-of-two-papuas",
    name: "A Tale of Two Papuas",
    eyebrow: "Papua",
    region: "Papua",
    nights: 7,
    level: "All certified levels",
    season: "TODO: season",
    teaser: "TODO: one-line teaser for A Tale of Two Papuas.",
    description: "TODO: full description for A Tale of Two Papuas.",
    detailExtra: "TODO: extra detail paragraph for A Tale of Two Papuas.",
    image: "hero-waow2",
    imageAlt: "Waow 2 under full sail.",
    photoCaption: "A Tale of Two Papuas",
  },

  // ---- Sulawesi ----
  {
    slug: "sulawesi-nirvana-and-lava",
    name: "Nirvana and Lava",
    eyebrow: "Sulawesi",
    region: "Sulawesi",
    nights: 7,
    level: "All certified levels",
    season: "TODO: season",
    teaser: "TODO: one-line teaser for Nirvana and Lava (Sulawesi).",
    description: "TODO: full description for Nirvana and Lava, a Sulawesi route.",
    detailExtra: "TODO: extra detail paragraph for Nirvana and Lava (Sulawesi).",
    image: "diver-reef",
    imageAlt: "A diver over a coral reef.",
    photoCaption: "Nirvana and Lava, Sulawesi",
  },
  {
    slug: "sulawesi-sponges-and-stilts",
    name: "Sponges and Stilts",
    eyebrow: "Sulawesi",
    region: "Sulawesi",
    nights: 10,
    level: "All certified levels",
    season: "TODO: season",
    teaser: "TODO: one-line teaser for Sponges and Stilts (Sulawesi).",
    description: "TODO: full description for Sponges and Stilts, a Sulawesi route.",
    detailExtra: "TODO: extra detail paragraph for Sponges and Stilts (Sulawesi).",
    image: "dive-gear-deck",
    imageAlt: "Dive gear ready on Waow 2's deck between dives.",
    photoCaption: "Sponges and Stilts, Sulawesi",
  },
  {
    slug: "sulawesi-sultans-and-tarsiers",
    name: "Sultans and Tarsiers",
    eyebrow: "Sulawesi",
    region: "Sulawesi",
    nights: 7,
    level: "All certified levels",
    season: "TODO: season",
    teaser: "TODO: one-line teaser for Sultans and Tarsiers (Sulawesi).",
    description: "TODO: full description for Sultans and Tarsiers, a Sulawesi route.",
    detailExtra: "TODO: extra detail paragraph for Sultans and Tarsiers (Sulawesi).",
    image: "dive-guide",
    imageAlt: "A dive guide briefing the group before a dive.",
    photoCaption: "Sultans and Tarsiers, Sulawesi",
  },

  // ---- Sunda Islands ----
  {
    slug: "sunda-east-meets-west",
    name: "East Meets West",
    eyebrow: "Sunda Islands",
    region: "Sunda Islands",
    nights: 11,
    level: "All certified levels",
    season: "End of May, one departure a year",
    teaser: "Flores to Bali, across the invisible border of Wallacea.",
    description: "Some routes become classics because a marketing department decided they should. This one became a classic because generations of divers sailed it, came home changed, and told everybody. You fly out to the far end of the archipelago, join Waow 2 in Flores, and spend eleven days sailing home.",
    detailExtra: "In between is a border that appears on no political map and still separates more deeply than most: you leave the Indonesia almost nobody has seen, and arrive in the one everybody thinks they know.",
    image: "komodo-island",
    imageAlt: "Padar Island's hills rising over the bays of Komodo National Park.",
    photoCaption: "East Meets West, Sunda Islands",
  },
  {
    slug: "sunda-west-meets-east",
    name: "West Meets East",
    eyebrow: "Sunda Islands",
    region: "Sunda Islands",
    nights: 11,
    level: "All certified levels",
    season: "TODO: season",
    teaser: "TODO: one-line teaser for West Meets East — the return leg, Bali to Flores.",
    description: "TODO: full description for West Meets East, a Sunda Islands route.",
    detailExtra: "TODO: extra detail paragraph for West Meets East (Sunda Islands).",
    image: "komodo-island",
    imageAlt: "Padar Island's hills rising over the bays of Komodo National Park.",
    photoCaption: "West Meets East, Sunda Islands",
  },
  {
    slug: "sunda-nirvana-and-lava",
    name: "Nirvana and Lava",
    eyebrow: "Sunda Islands",
    region: "Sunda Islands",
    nights: 7,
    level: "All certified levels",
    season: "TODO: season",
    teaser: "TODO: one-line teaser for Nirvana and Lava (Sunda Islands).",
    description: "TODO: full description for Nirvana and Lava, a Sunda Islands route.",
    detailExtra: "TODO: extra detail paragraph for Nirvana and Lava (Sunda Islands).",
    image: "sunset-deck",
    imageAlt: "Sunset view from Waow 2's deck.",
    photoCaption: "Nirvana and Lava, Sunda Islands",
  },
  {
    slug: "sunda-spices-and-snakes",
    name: "Spices and Snakes",
    eyebrow: "Sunda Islands",
    region: "Sunda Islands",
    nights: 8,
    level: "Advanced divers",
    season: "TODO: season",
    teaser: "TODO: one-line teaser for Spices and Snakes (Sunda Islands).",
    description: "TODO: full description for Spices and Snakes, a Sunda Islands route.",
    detailExtra: "TODO: extra detail paragraph for Spices and Snakes (Sunda Islands).",
    image: "alor-island",
    imageAlt: "A local fisherman paddling a traditional boat near a volcanic coastline in eastern Indonesia.",
    photoCaption: "Spices and Snakes, Sunda Islands",
  },
  {
    slug: "sunda-volcanoes-and-villages",
    name: "Volcanoes and Villages",
    eyebrow: "Sunda Islands",
    region: "Sunda Islands",
    nights: 10,
    level: "All certified levels",
    season: "April to May",
    teaser: "Ten to twelve days out of Maumere and back, entirely inside Alor and Solor.",
    description: "Most boats treat this archipelago as a stop on the way somewhere, dive four or five sites and carry on. This trip never leaves it.",
    detailExtra: "Out of Maumere and back, ten to twelve days entirely inside Alor and Solor, long enough to actually know the place instead of sampling it.",
    image: "alor-island",
    imageAlt: "A volcanic island seen from the water at Alor.",
    photoCaption: "Volcanoes and Villages, Sunda Islands",
  },

  // ---- Banda Sea ----
  {
    slug: "banda-spices-and-snakes",
    name: "Spices and Snakes",
    eyebrow: "Banda Sea",
    region: "Banda Sea",
    nights: 8,
    level: "Advanced divers",
    season: "TODO: season",
    teaser: "TODO: one-line teaser for Spices and Snakes (Banda Sea).",
    description: "TODO: full description for Spices and Snakes, a Banda Sea route.",
    detailExtra: "TODO: extra detail paragraph for Spices and Snakes (Banda Sea).",
    image: "alor-island",
    imageAlt: "A local fisherman paddling a traditional boat near a volcanic coastline in eastern Indonesia.",
    photoCaption: "Spices and Snakes, Banda Sea",
  },
];

if (typeof module !== "undefined" && module.exports) {
  module.exports = ITINERARIES;
}

/**
 * Routes that exist in two regions (same route, one page). Each region keeps its own entry (roster,
 * carousel, map panel, route image) but every link goes to the canonical page — always build links
 * with itineraryHref(slug), never by hand.
 */
const ITINERARY_CANONICAL = {
  "moluccas-corals-and-cloves": "papua-corals-and-cloves",
  "moluccas-spices-and-snakes": "sunda-spices-and-snakes",
  "banda-spices-and-snakes": "sunda-spices-and-snakes",
  "papua-forts-and-forests": "moluccas-forts-and-forests",
  "sulawesi-nirvana-and-lava": "sunda-nirvana-and-lava",
  "sulawesi-sultans-and-tarsiers": "moluccas-sultans-and-tarsiers",
};
function itineraryHref(slug) { return "itinerary.html?slug=" + encodeURIComponent(ITINERARY_CANONICAL[slug] || slug); }
