/**
 * Itinerary roster — single source of truth for the itinerary grid
 * (itineraries.html) and the itinerary detail template (itinerary.html?slug=).
 *
 * Add a route by adding an object here. Nothing else needs to change:
 * the grid card, the flip-card back, and the detail page are all rendered
 * from this array by itinerary-cards.js and itinerary.js respectively.
 *
 * Photos: most routes below are on generic Waow 2 / crew / dive photos,
 * not photos of the actual destination — TODO: replace each `image` with
 * real photography of that route once available.
 */

const ITINERARIES = [
  {
    slug: "east-meets-west",
    name: "East Meets West",
    eyebrow: "Signature Route",
    region: "Flores to Bali",
    nights: 11,
    level: "All certified levels",
    season: "End of May, one departure a year",
    teaser: "Flores to Bali, across the invisible border of Wallacea.",
    description: "Some routes become classics because a marketing department decided they should. This one became a classic because generations of divers sailed it, came home changed, and told everybody. You fly out to the far end of the archipelago, join Waow 2 in Flores, and spend eleven days sailing home.",
    detailExtra: "In between is a border that appears on no political map and still separates more deeply than most: you leave the Indonesia almost nobody has seen, and arrive in the one everybody thinks they know.",
    image: "komodo-island",
    imageAlt: "Padar Island's hills rising over the bays of Komodo National Park.",
    photoCaption: "East Meets West, Flores to Bali",
  },
  {
    slug: "dragon-ground",
    name: "Dragon Ground",
    eyebrow: "Signature Route",
    region: "Komodo National Park",
    nights: 7,
    level: "All certified levels",
    season: "Best April–November",
    teaser: "Komodo's bays, coral gardens, and dragons ashore.",
    description: "A seven-day passage through Komodo's hidden bays, coral gardens, and dragon-inhabited islands. Slow mornings, wild dives, and evenings under a sky with no city lights left to compete with.",
    detailExtra: "Most days start before the other boats are awake and end with the same anchorage to ourselves. We run this route more than any other — it's the one that made Waow 2's name, and the one we'd recommend if you can only do one.",
    image: "komodo-island",
    imageAlt: "Padar Island's hills rising over the bays of Komodo National Park.",
    photoCaption: "Dragon Ground, Komodo",
  },
  {
    slug: "raja-ampat-crossing",
    name: "Raja Ampat Crossing",
    eyebrow: "The Long Way Round",
    region: "Raja Ampat, West Papua",
    nights: 8,
    level: "All certified levels",
    season: "Best October–April",
    teaser: "Biodiverse reefs, karst lagoons, kayak-only coves.",
    description: "Eight days through some of the most biodiverse reefs on the planet, from Manta Sandy's cleaning stations to karst lagoons you reach by kayak, not engine.",
    detailExtra: "This is the route for guests who came for the fish count and stayed for the silence. Expect long tenders, short current, and a logbook that runs out of pages.",
    image: "raja-ampat",
    imageAlt: "Aerial view of karst islands and turquoise lagoons in Raja Ampat, West Papua.",
    photoCaption: "Raja Ampat Crossing",
  },
  {
    slug: "forgotten-islands",
    name: "The Forgotten Islands",
    eyebrow: "For Repeat Guests",
    region: "Banda Sea, Maluku",
    nights: 10,
    level: "Advanced divers",
    season: "Best October–March",
    teaser: "Volcanic walls, hammerhead passes, nutmeg villages.",
    description: "Ten days into water most divers only hear about — volcanic walls, hammerhead passes, and villages that still remember the nutmeg trade.",
    detailExtra: "The longest route we run, and the one our repeat guests ask for by name. Current can run strong here; we brief every site properly and skip the ones that aren't cooperating that day.",
    image: "banda-sea",
    imageAlt: "A volcanic island silhouette at sunset, with a traditional boat on calm water.",
    photoCaption: "The Forgotten Islands",
  },
  {
    slug: "alor-coast",
    name: "Alor & the Alorese Coast",
    eyebrow: "The Shorter Crossing",
    region: "Alor, East Nusa Tenggara",
    nights: 6,
    level: "All certified levels",
    season: "Best May–November",
    teaser: "Muck diving and wall diving in one afternoon.",
    description: "Six days of muck diving and wall diving in the same afternoon, along a coastline where the villages are as much the story as the reefs.",
    detailExtra: "Slower pace, shorter crossings, more time on deck. A good route if you want the diving without giving up your evenings to travel time.",
    image: "alor-island",
    imageAlt: "A local fisherman paddling a traditional boat near a volcanic coastline in eastern Indonesia.",
    photoCaption: "Alor & the Alorese Coast",
  },
  {
    slug: "komodo-express",
    name: "Komodo Express",
    eyebrow: "The Taster",
    region: "Komodo National Park",
    nights: 4,
    level: "Open water friendly",
    season: "Best April–November",
    teaser: "Four days, the highlight reel.",
    description: "A shorter cut through Komodo's best-known sites — Batu Bolong's current-swept wall, Manta Point, a dragon walk on Rinca.",
    detailExtra: "Built for guests with a long weekend and short patience for warm-up dives. Same boat, same crew, same anchorages we'd choose on the full route — just fewer of them.",
    image: "dive-gear-deck",
    imageAlt: "Dive gear laid out on Waow 2's deck, ready for a morning briefing.",
    photoCaption: "Komodo Express",
  },
  {
    slug: "south-komodo",
    name: "South Komodo & Sumbawa",
    eyebrow: "Cold Water, Big Animals",
    region: "South Komodo, Sumbawa",
    nights: 8,
    level: "Advanced divers",
    season: "Best June–October",
    teaser: "Colder upwellings, the animals that come with them.",
    description: "Colder upwellings, stronger current, and the animals that come with both — mola mola sightings some seasons, schooling hammerheads most.",
    detailExtra: "Not the gentle side of Komodo. Bring a hood and a 7mm — the water here runs a good five degrees colder than the north side, and it's worth every shiver.",
    image: "manta-ray",
    imageAlt: "A manta ray gliding over the reef.",
    photoCaption: "South Komodo & Sumbawa",
  },
  {
    slug: "dampier-misool",
    name: "Dampier Strait & Misool",
    eyebrow: "Southern Raja Ampat",
    region: "Raja Ampat, West Papua",
    nights: 9,
    level: "All certified levels",
    season: "Best November–March",
    teaser: "Soft coral bommies, decade-old no-take lagoons.",
    description: "Nine days working the reefs between Waigeo and Misool — soft coral bommies stacked with anthias, lagoons closed to fishing for a decade and it shows.",
    detailExtra: "Slow current, endless macro, the diving Raja Ampat is famous for. We keep the schedule loose here on purpose; some sites deserve a second dive the same afternoon.",
    image: "diver-reef",
    imageAlt: "A diver exploring a vivid coral reef.",
    photoCaption: "Dampier Strait & Misool",
  },
  {
    slug: "wayag-circuit",
    name: "The Wayag Circuit",
    eyebrow: "The Postcard Route",
    region: "Raja Ampat, West Papua",
    nights: 8,
    level: "All certified levels",
    season: "Best October–April",
    teaser: "The karst lagoon everyone's seen a photo of.",
    description: "North to the karst islands everyone's seen a photo of, minus the crowd. A viewpoint hike over the lagoon at dawn, then back in the water before the day boats arrive.",
    detailExtra: "We time the crossing to arrive overnight, so the first light at the viewpoint is ours alone. The climb is short and steep — worth doing once, even if you skip the second morning.",
    image: "waow2-portrait",
    imageAlt: "Waow 2 at anchor against a backdrop of limestone islands.",
    photoCaption: "The Wayag Circuit",
  },
  {
    slug: "wakatobi-wander",
    name: "Wakatobi Wander",
    eyebrow: "The Far Side",
    region: "Wakatobi National Park",
    nights: 10,
    level: "All certified levels",
    season: "Best April–November",
    teaser: "A marine park most guests have never heard of.",
    description: "Ten days in a marine park most guests have never heard of and won't stop talking about after. Wall after wall of untouched reef, and villages built entirely on stilts over the lagoon.",
    detailExtra: "It's a longer transit to get here, which is exactly why it stays this good. We run it a handful of times a season, not every charter.",
    image: "sunset-deck",
    imageAlt: "Waow 2's deck at sunset.",
    photoCaption: "Wakatobi Wander",
  },
  {
    slug: "ambon-lease",
    name: "Ambon & the Lease Islands",
    eyebrow: "Critter Country",
    region: "Ambon, Maluku",
    nights: 6,
    level: "All certified levels",
    season: "Best October–April",
    teaser: "Rhinopias, mimic octopus, a stage made of sand.",
    description: "Muck diving at its strangest — rhinopias, psychedelic frogfish, mimic octopus working a sand slope like a stage.",
    detailExtra: "Six nights for divers who'd rather find one impossible creature than count fish. Bring a torch and patience; the best finds here reward the divers who stop moving.",
    image: "dive-guide",
    imageAlt: "One of Waow 2's dive guides, mask in hand.",
    photoCaption: "Ambon & the Lease Islands",
  },
  {
    slug: "spice-route",
    name: "Spice Route: Banda to Ambon",
    eyebrow: "History Below and Above",
    region: "Banda Sea to Ambon",
    nights: 9,
    level: "Advanced divers",
    season: "Best October–March",
    teaser: "The old nutmeg trading route, run the slow way.",
    description: "The old nutmeg trading route, run the slow way. Volcanic walls that drop past a hundred metres, forts built by three different colonial powers, and the quiet of islands the spice wars once fought over.",
    detailExtra: "Half history, half current-line. We'll go ashore at a couple of the old forts on calm-weather days — the reefs are the main event, but the ruins are worth the detour.",
    image: "waow2-detail",
    imageAlt: "Detail of Waow 2's rigging and timber deck.",
    photoCaption: "Spice Route",
  },
  {
    slug: "halmahera-hidden-reefs",
    name: "Halmahera's Hidden Reefs",
    eyebrow: "Rarely Dived",
    region: "Halmahera, North Maluku",
    nights: 8,
    level: "Advanced divers",
    season: "Best November–April",
    teaser: "Reefs most logbooks have never recorded.",
    description: "Reefs most logbooks have never recorded. We go slow, check conditions daily, and turn back if the crossing doesn't cooperate.",
    detailExtra: "This is the route for guests who want somewhere genuinely unfamiliar, and who understand that the plan may change with the weather. It usually does, once.",
    image: "captain-wheel",
    imageAlt: "The captain at Waow 2's wheel.",
    photoCaption: "Halmahera's Hidden Reefs",
  },
  {
    slug: "triton-bay",
    name: "Triton Bay & the Fak Fak Coast",
    eyebrow: "West Papua, Further East",
    region: "Triton Bay, West Papua",
    nights: 9,
    level: "Advanced divers",
    season: "Best October–April",
    teaser: "Walking sharks by night, a bay that barely moves.",
    description: "Karst islands, walking sharks on the night dive, and a bay so sheltered the water barely moves.",
    detailExtra: "Remote even by our standards — the closest resupply is two days out, so we provision heavy and plan loose. Worth it for a bay this quiet.",
    image: "crew-hospitality",
    imageAlt: "A crew member setting out drinks on deck.",
    photoCaption: "Triton Bay & the Fak Fak Coast",
  },
  {
    slug: "cenderawasih-whale-sharks",
    name: "Cenderawasih Bay Whale Sharks",
    eyebrow: "The Big Encounter",
    region: "Cenderawasih Bay, West Papua",
    nights: 7,
    level: "All certified levels",
    season: "Best October–March",
    teaser: "Fishing platforms where whale sharks wait for scraps.",
    description: "Fishing platforms where whale sharks have learned to wait for scraps, and guests learn to hold still.",
    detailExtra: "Seven days built around one encounter, with enough reef diving either side to fill the logbook. Snorkel or scuba both work here — the sharks don't mind either way.",
    image: "chef-galley",
    imageAlt: "Waow 2's chef at work in the galley.",
    photoCaption: "Cenderawasih Bay",
  },
  {
    slug: "lembata-whalers-coast",
    name: "Lembata & the Whale Hunters' Coast",
    eyebrow: "Volcanoes and Villages",
    region: "Lembata, East Nusa Tenggara",
    nights: 6,
    level: "All certified levels",
    season: "Best May–October",
    teaser: "Past an active volcano to villages that still hunt by hand.",
    description: "A short, current-swept crossing past an active volcano to villages that still hunt by hand-thrown harpoon, the way they have for centuries.",
    detailExtra: "Diving by day, longhouse visits by evening. We time the village stop for a day the season allows — it isn't guaranteed, and we won't pretend it is.",
    image: "deckhand-rope",
    imageAlt: "A deckhand coiling line on the foredeck.",
    photoCaption: "Lembata & the Whale Hunters' Coast",
  },
  {
    slug: "flores-volcano-traverse",
    name: "Flores Volcano Traverse",
    eyebrow: "Easy Days",
    region: "Flores, East Nusa Tenggara",
    nights: 5,
    level: "Open water friendly",
    season: "Best April–November",
    teaser: "Reef diving by morning, crater lakes by afternoon.",
    description: "The gentlest route we run — reef diving in the mornings, a hike up to Kelimutu's three-coloured crater lakes on the one day we're ashore.",
    detailExtra: "A good first liveaboard, or a good rest between harder ones. Nobody's rushing you into a wetsuit on this route.",
    image: "guests-table",
    imageAlt: "Guests sharing a meal at Waow 2's saloon table.",
    photoCaption: "Flores Volcano Traverse",
  },
  {
    slug: "sumba-solitude",
    name: "Sumba Solitude",
    eyebrow: "Off the Log",
    region: "Sumba, East Nusa Tenggara",
    nights: 7,
    level: "All certified levels",
    season: "Best June–October",
    teaser: "Reefs that have barely met a dive boat.",
    description: "South of everywhere else we go, where the swell comes straight off the open ocean and the reefs have barely met a dive boat.",
    detailExtra: "Quiet in a way the busier routes aren't. Expect a longer surface interval between sites, and a coastline that looks the same as it did fifty years ago.",
    image: "interior-saloon",
    imageAlt: "The quiet of Waow 2's saloon interior.",
    photoCaption: "Sumba Solitude",
  },
  {
    slug: "timor-strait-crossing",
    name: "Timor Strait Crossing",
    eyebrow: "Advanced Only",
    region: "Alor to Timor",
    nights: 8,
    level: "Advanced divers",
    season: "Best June–October",
    teaser: "Drift dives measured in knots, not fin kicks.",
    description: "An extension past Alor into water that moves with real conviction — drift dives measured in knots, not fin kicks.",
    detailExtra: "For guests who've done the Alorese Coast route and want the harder sequel. Logged current dives and a recent medical are non-negotiable here.",
    image: "boat-construction",
    imageAlt: "Waow 2's ironwood hull, photographed during her build.",
    photoCaption: "Timor Strait Crossing",
  },
  {
    slug: "derawan-sangalaki",
    name: "Derawan & Sangalaki",
    eyebrow: "North Detour",
    region: "Derawan Archipelago, East Kalimantan",
    nights: 7,
    level: "All certified levels",
    season: "Best April–October",
    teaser: "Turtle-crowded reefs and a lake of stingless jellyfish.",
    description: "A rare northward season, run maybe once a year — turtle-crowded reefs, a lake of stingless jellyfish you swim through rather than around.",
    detailExtra: "Manta cleaning stations working overtime, and a landscape that looks nothing like the rest of our routes. We announce the dates early — this one fills fast.",
    image: "steward-towels",
    imageAlt: "A steward folding towels for the cabins.",
    photoCaption: "Derawan & Sangalaki",
  },
  {
    slug: "grand-traverse",
    name: "The Grand Traverse: Komodo to Raja Ampat",
    eyebrow: "The Big One",
    region: "Komodo to Raja Ampat",
    nights: 21,
    level: "Advanced divers",
    season: "Once a year, best November",
    teaser: "The full length of the map, no repeated anchorage.",
    description: "Three weeks, the full length of the route map, no repeated anchorage.",
    detailExtra: "We run it once a season for guests who've done the shorter crossings and are done pretending they don't want the whole thing. Provisioning alone takes a week.",
    image: "hero-waow2",
    imageAlt: "Waow 2 under full sail.",
    photoCaption: "The Grand Traverse",
  },
];

if (typeof module !== "undefined" && module.exports) {
  module.exports = ITINERARIES;
}
